// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8RC4IMwx8p-y4gv9Bt7qhKmNIAX_VYRA',
    appId: '1:965550030175:web:e3fb7bd60147ceab02caea',
    messagingSenderId: '965550030175',
    projectId: 'taskmanager2057',
    authDomain: 'taskmanager2057.firebaseapp.com',
    storageBucket: 'taskmanager2057.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiuMsrpkZOWyEdCWg20DSsToMuamNleao',
    appId: '1:965550030175:android:f83e0492204090d102caea',
    messagingSenderId: '965550030175',
    projectId: 'taskmanager2057',
    storageBucket: 'taskmanager2057.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKT6r_YlA01GUUILxWflEU34chwaJTr4k',
    appId: '1:965550030175:ios:524ac40ad160ccbc02caea',
    messagingSenderId: '965550030175',
    projectId: 'taskmanager2057',
    storageBucket: 'taskmanager2057.appspot.com',
    iosClientId: '965550030175-c1u06svau97ds4st3gq10odjn8dl6224.apps.googleusercontent.com',
    iosBundleId: 'com.example.shreyaTaskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKT6r_YlA01GUUILxWflEU34chwaJTr4k',
    appId: '1:965550030175:ios:524ac40ad160ccbc02caea',
    messagingSenderId: '965550030175',
    projectId: 'taskmanager2057',
    storageBucket: 'taskmanager2057.appspot.com',
    iosClientId: '965550030175-c1u06svau97ds4st3gq10odjn8dl6224.apps.googleusercontent.com',
    iosBundleId: 'com.example.shreyaTaskApp',
  );
}
